name: test-workflow
on:
  push:
    branches:
      - 'main'
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code from my repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: mvn clean install
      - name: Run my all test 
        run: mvn test
      

