name: test-workflow
on:  
  push:
    branches:
      - 'main'
  workflow_dispatch:
    branches:
      - 'main'
  pull_request:  
    types:  
    - opened
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code from my repository
        uses: actions/checkout@v4
      - name: Add Java, because it was not supported
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'      
      - name: Install dependencies
        run: mvn clean install
      - name: Run my all test 
        run: mvn test
  upload-job:
    needs: test-job
    runs-on: ubuntu-latest
    outputs:
      my-output-first-key: ${{ steps.output_value_for_other_job.outputs.output_for_other_jar_name }}
    steps:
      - name: Get the code from my repository
        uses: actions/checkout@v4
      - name: Add Java, because it was not supported
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'      
      - name: Install dependencies
        run: mvn clean install
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Create upload java artifact
          path: |
            target
            !target/*original
      - name: Output value for other job
        id: output_value_for_other_job
        run: | 
          fileName=$(find target/*.jar -type f)
          echo "output_for_other_jar_name=$fileName" >> "$GITHUB_OUTPUT" 
      - name: Output value for the same job
        id: output_value_for_the_same_job
        run: echo "output_for_same_job_jar_name='Ezt az értéket szeretném látni ebben a job-ban'" >> "$GITHUB_OUTPUT"   
      - name: Read the value which created for the same job
        id: read_simple_value_to_use_in_the_same_job
        run:  echo ${{steps.output_value_for_the_same_job.outputs.output_for_same_job_jar_name}}    
  download-job:  
    needs: upload-job
    runs-on: ubuntu-latest
    steps: 
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Create upload java artifact    
      - name: Files list in directory 
        run: ls
      - name: Write out jar file name 
        run:  echo ${{needs.upload-job.outputs.my-output-first-key}}    
         


