name: test-workflow
on:  
  push:
    branches:
      - 'main'
  workflow_dispatch:
    branches:
      - 'main'
  pull_request:  
    types:  
    - opened
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code from my repository
        uses: actions/checkout@v4
      - name: Add Java, because it was not supported
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'      
      - name: Install dependencies
        run: mvn clean install
      - name: Run my all test 
        run: mvn test
  upload-job:
    needs: test-job
    runs-on: ubuntu-latest
    outputs:
      my-output-first-key: ${{ steps.jar_file_name_output.outputs.jar_name }}
    steps:
      - name: Get the code from my repository
        uses: actions/checkout@v4
      - name: Add Java, because it was not supported
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'      
      - name: Install dependencies
        run: mvn clean install
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Create upload java artifact
          path: |
            target
            !target/*original
      - name: Find generated jar file name and save in a variable to use in output
        id: jar_file_name_output
        run: $(echo "jar_name" | find target -type f `ghes-0.0.1-SNAPSHOT.jar`)
      - name: Find generated jar file name and save in GITHUB_OUTPUT variable    
        run:  echo $my-output-first-key       
  download-job:  
    needs: upload-job
    runs-on: ubuntu-latest
    steps: 
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Create upload java artifact    
      - name: Files list in directory 
        run: ls
         


